/*
 */
package mrnock.powerfitbeans;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mrnock.powerfitbeans.dataacccess.Controller;
import mrnock.powerfitbeans.dialogs.DlgLogin;
import mrnock.powerfitbeans.dialogs.PnlIntentos;
import mrnock.powerfitbeans.dialogs.PnlWelcome;
import mrnock.powerfitbeans.dto.Intent;

/**
 *
 * @author SilviaRichard
 */
public class MainForm extends javax.swing.JFrame {

    private DlgLogin dlgLogin;
    private PnlWelcome pnlWelcome;
    private Controller controller;
    private PnlIntentos pnlIntentos;
    //private PanelAuxiliar panelAuxiliar;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setSize(1000, 500);
        setResizable(false);
        setLocationRelativeTo(null);

        // dlgLogin = new DlgLogin(this);
        // dlgLogin.setBounds(450, 10, 330, 440);
        // TEST
        controller = new Controller(this);
        /*ArrayList<Intent> intentos = controller.getAttemptsPendingReview();

        //ArrayList<Intent> intentos = new ArrayList<Intent>();
        try {
            pnlIntentos = new PnlIntentos(this, intentos);
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }*/

        // getContentPane().remove(lblWelcomeImage);
        // getContentPane().add(pnlIntentos, 0);
        pnlWelcome = new PnlWelcome(this);
        getContentPane().add(pnlWelcome);
        pnlWelcome.setBounds(450, 10, 330, 440);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblWelcomeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/432x432_PowerFitBeans.png"))); // NOI18N
        lblWelcomeImage.setMaximumSize(new java.awt.Dimension(112, 108));
        lblWelcomeImage.setMinimumSize(new java.awt.Dimension(112, 108));
        getContentPane().add(lblWelcomeImage);
        lblWelcomeImage.setBounds(10, 10, 432, 432);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void validateLogin() {

        dlgLogin = new DlgLogin(this);
        dlgLogin.setVisible(true);
    }

    public boolean validateUser(String email, char[] password) {

        //JOptionPane.showMessageDialog(this, "El email o password es incorrecto", "Error de Login", JOptionPane.ERROR_MESSAGE);
        ArrayList<Intent> intentos = controller.getAttemptsPendingReview();

        boolean ret = controller.validateLogin(email, password);
        if (!ret) {
            JOptionPane.showMessageDialog(this, "El email o password es incorrecto", "Error de Login", JOptionPane.ERROR_MESSAGE);
        } else {
            dlgLogin.dispose();
            try {
                // panelAuxiliar = new PanelAuxiliar();
                pnlIntentos = new PnlIntentos(this, intentos);
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            getContentPane().removeAll();
            getContentPane().add(pnlIntentos);
            //repaint();
            pnlIntentos.updateUI();
            pnlIntentos.playSelectedVideo(0);
        }
        /*
        if (ret) {
            try {
                ArrayList<Intent> intentos = controller.getAttemptsPendingReview();

                pnlIntentos = new PnlIntentos(this, intentos);
                getContentPane().removeAll();
                getContentPane().add(pnlIntentos);
                pnlIntentos.repaint();
                this.repaint();
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }*/
        return ret;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblWelcomeImage;
    // End of variables declaration//GEN-END:variables
}
