/*
 */
package mrnock.powerfitbeans;

import mrnock.powerfitbeans.dialogs.Login;

/**
 *
 * @author SilviaRichard
 */
public class MainForm extends javax.swing.JFrame {
    
    private Login dlgLogin;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setSize(800,500);
        setResizable(false);
        setLocationRelativeTo(null);
        
        dlgLogin = new Login();
        dlgLogin.setBounds(450, 10, 330, 440);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblWelcomeImage = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblMoreInfo = new javax.swing.JLabel();
        lblUrlWeb = new javax.swing.JLabel();
        lblAccessLogin = new javax.swing.JLabel();
        lblIconLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblWelcomeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/432x432_PowerFitBeans.png"))); // NOI18N
        lblWelcomeImage.setMaximumSize(new java.awt.Dimension(112, 108));
        lblWelcomeImage.setMinimumSize(new java.awt.Dimension(112, 108));
        getContentPane().add(lblWelcomeImage);
        lblWelcomeImage.setBounds(10, 10, 432, 432);

        pnlLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLogin.setPreferredSize(new java.awt.Dimension(432, 432));
        pnlLogin.setLayout(null);

        lblWelcome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome to the Power Fit Beans App");
        pnlLogin.add(lblWelcome);
        lblWelcome.setBounds(8, 8, 310, 40);

        lblMoreInfo.setText("More info: ");
        pnlLogin.add(lblMoreInfo);
        lblMoreInfo.setBounds(80, 390, 60, 16);

        lblUrlWeb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUrlWeb.setForeground(new java.awt.Color(0, 0, 255));
        lblUrlWeb.setText("www.powerfitbeans.com");
        lblUrlWeb.setToolTipText("https://paucasesnovescifp.cat/");
        lblUrlWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLogin.add(lblUrlWeb);
        lblUrlWeb.setBounds(140, 390, 160, 20);

        lblAccessLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAccessLogin.setText("Click to login:");
        pnlLogin.add(lblAccessLogin);
        lblAccessLogin.setBounds(40, 190, 150, 30);

        lblIconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-64.png"))); // NOI18N
        lblIconLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconLoginMouseClicked(evt);
            }
        });
        pnlLogin.add(lblIconLogin);
        lblIconLogin.setBounds(200, 180, 70, 50);

        getContentPane().add(pnlLogin);
        pnlLogin.setBounds(450, 10, 330, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblIconLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconLoginMouseClicked
        dlgLogin.setVisible(true);
        pnlLogin.setVisible(false);
    }//GEN-LAST:event_lblIconLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblAccessLogin;
    private javax.swing.JLabel lblIconLogin;
    private javax.swing.JLabel lblMoreInfo;
    private javax.swing.JLabel lblUrlWeb;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcomeImage;
    private javax.swing.JPanel pnlLogin;
    // End of variables declaration//GEN-END:variables
}
