/*
 */
package mrnock.powerfitbeans.dialogs;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

/**
 *
 * @author SilviaRichard
 */
public class JFrameVLCPlayer extends javax.swing.JFrame {

    private EmbeddedMediaPlayerComponent mediaPlayer;
    private JFileChooser fileChooser;
    private boolean isPlaying = false;

    /**
     * Creates new form JFrameVLCPlayer
     */
    public JFrameVLCPlayer() {
        initComponents();
        fileChooser = new JFileChooser();
        mediaPlayer = new EmbeddedMediaPlayerComponent();
        //Add component and center its position within the panel
        pnlVideoPlayer.add(mediaPlayer, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVideosPath = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVideos = new javax.swing.JList<>();
        pnlVideoPlayer = new javax.swing.JPanel();
        btnPauseResumeVideo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtVideosPath.setText("Pick folder...");
        getContentPane().add(txtVideosPath);
        txtVideosPath.setBounds(52, 39, 447, 22);

        btnOpen.setText("Open...");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpen);
        btnOpen.setBounds(427, 73, 72, 23);

        lstVideos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVideosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstVideos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(52, 124, 203, 326);

        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player"));
        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlVideoPlayer);
        pnlVideoPlayer.setBounds(339, 160, 420, 290);

        btnPauseResumeVideo.setText("Pause");
        btnPauseResumeVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseResumeVideoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPauseResumeVideo);
        btnPauseResumeVideo.setBounds(491, 462, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        //Only directories not files
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        //Variable to get button pressed (Open or Cancel)
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            txtVideosPath.setText(fileChooser.getSelectedFile().getAbsolutePath());
            File videosFolder = new File(fileChooser.getSelectedFile().getAbsolutePath());
            File[] videos = videosFolder.listFiles();
            DefaultListModel dlm = new DefaultListModel();

            for (int i = 0; i < videos.length; i++) {
                File video = new File(videos[i].getAbsolutePath());
                if (video.isFile()) {
                    dlm.addElement(video.getName());
                }
            }
            lstVideos.removeAll();
            lstVideos.setModel(dlm);
        }


    }//GEN-LAST:event_btnOpenActionPerformed

    private void lstVideosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVideosValueChanged
        //Adjunt mouse click
        if (evt.getValueIsAdjusting()) {
            return;
        }
        String videoFileFolder = fileChooser.getSelectedFile().getAbsolutePath();
        String videoFileAbsolutePath = videoFileFolder + File.separator + lstVideos.getSelectedValue();
        mediaPlayer.mediaPlayer().media().play(videoFileAbsolutePath);
        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player - " + lstVideos.getSelectedValue()));
        btnPauseResumeVideo.setText("Pause");
        isPlaying = true;
    }//GEN-LAST:event_lstVideosValueChanged

    private void btnPauseResumeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseResumeVideoActionPerformed
        if (isPlaying) {
            mediaPlayer.mediaPlayer().controls().pause();
            isPlaying = false;
            btnPauseResumeVideo.setText("Resume");
        } else{
            mediaPlayer.mediaPlayer().controls().start();
            isPlaying = true;
            btnPauseResumeVideo.setText("Pause");
        }
    }//GEN-LAST:event_btnPauseResumeVideoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVLCPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVLCPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVLCPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVLCPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVLCPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPauseResumeVideo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstVideos;
    private javax.swing.JPanel pnlVideoPlayer;
    private javax.swing.JTextField txtVideosPath;
    // End of variables declaration//GEN-END:variables
}
