/*
 */
package mrnock.powerfitbeans.dialogs;

import java.awt.BorderLayout;
import java.io.File;
import java.util.ArrayList;
import mrnock.powerfitbeans.MainForm;
import mrnock.powerfitbeans.dto.Intent;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

/**
 *
 * @author SilviaRichard
 */
public class JFrameIntentos extends javax.swing.JFrame {
    
    
    MainForm mainForm;
    ArrayList<Intent> intentos;
    private EmbeddedMediaPlayerComponent mediaPlayer;
    //private boolean isPlaying = false;
    
    String VIDEO_PATH = "C:\\Users\\SilviaRichard\\AppData\\Local\\Simulap\\videos\\999661693.mp4";


    /**
     * Creates new form JFrameIntentos
     */
    public JFrameIntentos() {
        initComponents();
         
        mediaPlayer = new EmbeddedMediaPlayerComponent();
        //Add component and center its position within the panel
        pnlVideoPlayer.add(mediaPlayer, BorderLayout.CENTER);
        pnlVideoPlayer.setVisible(true);
        setBounds(10, 10, 1000, 432);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVideoPlayer = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());

        btnPlay.setText("jButton1");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        pnlVideoPlayer.add(btnPlay, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlVideoPlayer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //"C:\Users\SilviaRichard\AppData\Local\Simulap\videos\999661693.mp4"
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        String videoFileAbsolutePath = VIDEO_PATH;
        mediaPlayer.mediaPlayer().media().play(videoFileAbsolutePath);
        //pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player - " + lstVideos.getSelectedValue()));
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameIntentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameIntentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameIntentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameIntentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameIntentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JPanel pnlVideoPlayer;
    // End of variables declaration//GEN-END:variables
}
