package mrnock.powerfitbeans.dialogs;

import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Iterator;
import javafx.beans.binding.Bindings;
import javafx.beans.property.DoubleProperty;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.stage.Screen;
import javax.swing.DefaultListModel;
import mrnock.powerfitbeans.dto.Intent;

/**
 *
 * @author SilviaRichard
 */
public class PnlIntentos extends javax.swing.JPanel {

    /**
     * Creates new form PnlIntentos
     *
     * @param intentos
     * @throws java.net.URISyntaxException
     * @throws java.io.IOException
     */
    public PnlIntentos(ArrayList<Intent> intentos) throws URISyntaxException, IOException {
        initComponents();

        Iterator<Intent> iterator = intentos.iterator();
        DefaultListModel defaultlm = (DefaultListModel) lstPendingReviews.getModel();
        while (iterator.hasNext()) {

            defaultlm.addElement(iterator.next().getNomUsuari() + " " + iterator.next().getNomExercici());
        }

        lstPendingReviews.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Elemento 1", "Elemento 2"};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });

        if (!intentos.isEmpty()) {

            /*
            final JFXPanel VFXPanel = new JFXPanel();

            Media m = new Media(getClass().getResource("/videos/" + intentos.get(0).getVideofile()).toString());

            MediaPlayer player = new MediaPlayer(m);
            MediaView viewer = new MediaView(player);

            StackPane root = new StackPane();
            Scene scene = new Scene(root);

            // center video position
            //javafx.geometry.Rectangle2D screen = Screen.getPrimary().getVisualBounds();
            viewer.setX(0);
            viewer.setY(0);
            //viewer.setX((screen.getWidth() - videoPanel.getWidth()) / 2);
            //viewer.setY((screen.getHeight() - videoPanel.getHeight()) / 2);

            // resize video based on screen size
            DoubleProperty width = viewer.fitWidthProperty();
            DoubleProperty height = viewer.fitHeightProperty();
            width.bind(Bindings.selectDouble(viewer.sceneProperty(), "width"));
            height.bind(Bindings.selectDouble(viewer.sceneProperty(), "height"));
            viewer.setPreserveRatio(true);

            // add video to stackpane
            root.getChildren().add(viewer);

            VFXPanel.setScene(scene);
            //player.play();
            //videoPanel.setLayout(new BorderLayout());
            //videoPanel.add(VFXPanel, BorderLayout.CENTER); 
            add(VFXPanel);
             */
        }

        /*
                mediaURL = getClass().getResource("/videos/" + intentos.get(0).getVideofile());
                //create the media player with the media url
                Player mediaPlayer = Manager.createRealizedPlayer(mediaURL);
                //get components for video and playback controls
                Component video = mediaPlayer.getVisualComponent();
                Component controls = mediaPlayer.getControlPanelComponent();
                add(video);
                add(controls);
            } catch (MalformedURLException ex) {
                Logger.getLogger(PnlIntentos.class.getName()).log(Level.SEVERE, null, ex);
            }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPendingReviews = new javax.swing.JList<>();

        setLayout(null);

        lstPendingReviews.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Elemento 1", "Elemento 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstPendingReviews);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 150, 146);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstPendingReviews;
    // End of variables declaration//GEN-END:variables
}
