package mrnock.powerfitbeans.dialogs;

import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import mrnock.powerfitbeans.MainForm;
import mrnock.powerfitbeans.dto.Intent;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

/**
 *
 * @author SilviaRichard
 */
public class PnlIntentos extends javax.swing.JPanel {
    
    MainForm mainForm;
    ArrayList<Intent> intentos;
    private EmbeddedMediaPlayerComponent mediaPlayer;
    private boolean isPlaying = false;
    
    String VIDEO_PATH = "C:\\Users\\SilviaRichard\\AppData\\Local\\Simulap\\videos";

    /**
     * Creates new form PnlIntentos
     *
     * @param mainForm
     * @param intentos
     * @throws java.net.URISyntaxException
     * @throws java.io.IOException
     */
    public PnlIntentos(MainForm mainForm, ArrayList<Intent> intentos) throws URISyntaxException, IOException {
        initComponents();
        this.intentos = intentos;
        
        mediaPlayer = new EmbeddedMediaPlayerComponent();
        //Add component and center its position within the panel
        pnlVideoPlayer.add(mediaPlayer, BorderLayout.CENTER);
        pnlVideoPlayer.setVisible(true);
        setBounds(10, 10, 1000, 432);

        //Iterator<Intent> iterator = intentos.iterator();
        DefaultTableModel dtm = (DefaultTableModel) tblPendingReviews.getModel();
        
        for (Intent i : intentos) {
            dtm.insertRow(dtm.getRowCount(), new Object[]{
                i.getTimestamp_Inici(),
                i.getNomUsuari(),
                i.getNomExercici()
            }
            );
        }
        
        tblPendingReviews.setRowSelectionInterval(0, 0);
   
        
        tblPendingReviews.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evt) {
                // do some actions here, for example
                // print first column value from selected row
                if (evt.getValueIsAdjusting()) {
                    return;
                }
                playSelectedVideo(tblPendingReviews.getSelectedRow());
            }
        });
             
        if (!intentos.isEmpty()) {
            playSelectedVideo(0);
        }
    }
    
    private void playSelectedVideo(int row) {
        
        String videoName = intentos.get(row).getVideoFile();

        //String videoFileFolder = fileChooser.getSelectedFile().getAbsolutePath();
        String videoFileAbsolutePath = VIDEO_PATH + File.separator + videoName;
        
        File f = new File(videoFileAbsolutePath);
        if (f.exists()) {
            // TODO: Comprobar si el video existe
            
            mediaPlayer.mediaPlayer().media().play(videoFileAbsolutePath);
           
            pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player - " + videoName));
           
            //btnPauseResumeVideo.setText("Pause");
            isPlaying = true;
        }        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendingReviews = new javax.swing.JTable();
        lblLogoImg = new javax.swing.JLabel();
        lblWelcomeInstructor = new javax.swing.JLabel();
        pnlVideoPlayer = new javax.swing.JPanel();
        lblPendingReview = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(1000, 432));
        setLayout(null);

        tblPendingReviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "User", "Exercici"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPendingReviews);
        if (tblPendingReviews.getColumnModel().getColumnCount() > 0) {
            tblPendingReviews.getColumnModel().getColumn(0).setResizable(false);
            tblPendingReviews.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(28, 132, 390, 154);

        lblLogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/54x54_PowerFitBeans.png"))); // NOI18N
        lblLogoImg.setText("jLabel1");
        add(lblLogoImg);
        lblLogoImg.setBounds(815, 25, 56, 52);

        lblWelcomeInstructor.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblWelcomeInstructor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWelcomeInstructor.setText("Welcome <Instructor Name>");
        add(lblWelcomeInstructor);
        lblWelcomeInstructor.setBounds(368, 24, 429, 52);

        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Playing <Ejercicio>"));
        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());
        add(pnlVideoPlayer);
        pnlVideoPlayer.setBounds(476, 94, 530, 370);

        lblPendingReview.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPendingReview.setText("Pending Review");
        add(lblPendingReview);
        lblPendingReview.setBounds(28, 104, 149, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogoImg;
    private javax.swing.JLabel lblPendingReview;
    private javax.swing.JLabel lblWelcomeInstructor;
    private javax.swing.JPanel pnlVideoPlayer;
    private javax.swing.JTable tblPendingReviews;
    // End of variables declaration//GEN-END:variables
}
