package mrnock.powerfitbeans.dialogs;

import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import mrnock.powerfitbeans.MainForm;
import mrnock.powerfitbeans.dto.Intent;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

/**
 *
 * @author SilviaRichard
 */
public class PnlIntentos extends javax.swing.JPanel {

    MainForm mainForm;
    ArrayList<Intent> intentos;
    private EmbeddedMediaPlayerComponent mediaPlayer;

    String VIDEO_PATH = "C:\\Users\\SilviaRichard\\AppData\\Local\\Simulap\\videos";

    /**
     * Creates new form PnlIntentos
     *
     * @param mainForm
     * @param intentos
     * @throws java.net.URISyntaxException
     * @throws java.io.IOException
     */
    public PnlIntentos(MainForm mainForm, ArrayList<Intent> intentos) throws URISyntaxException, IOException {
        initComponents();
        this.intentos = intentos;
        this.mainForm = mainForm;

        mediaPlayer = new EmbeddedMediaPlayerComponent();
        //Add component and center its position within the panel
        pnlVideoPlayer.add(mediaPlayer, BorderLayout.CENTER);
        setBounds(10, 10, 900, 432);

        DefaultTableModel dtm = (DefaultTableModel) tblPendingReviews.getModel();

        for (Intent i : intentos) {
            dtm.insertRow(dtm.getRowCount(), new Object[]{
                i.getTimestamp_Inici(),
                i.getNomUsuari(),
                i.getNomExercici()
            }
            );
        }
        tblPendingReviews.setModel(dtm);
        tblPendingReviews.setRowSelectionInterval(0, 0);

        tblPendingReviews.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evt) {
                if (evt.getValueIsAdjusting()) {
                    return;
                }
                playSelectedVideo(tblPendingReviews.getSelectedRow());
            }
        });

    }

    public void playSelectedVideo(int row) {

        String videoName = intentos.get(row).getVideoFile();

        String videoFileAbsolutePath = VIDEO_PATH + File.separator + videoName;

        File f = new File(videoFileAbsolutePath);
        if (f.exists()) {

            mediaPlayer.mediaPlayer().media().play(videoFileAbsolutePath);
            pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player - " + videoName));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendingReviews = new javax.swing.JTable();
        lblLogoImg = new javax.swing.JLabel();
        lblWelcomeInstructor = new javax.swing.JLabel();
        pnlVideoPlayer = new javax.swing.JPanel();
        lblPendingReview = new javax.swing.JLabel();
        btnVerUsuarios = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(1000, 432));

        tblPendingReviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "User", "Exercici"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPendingReviews);
        if (tblPendingReviews.getColumnModel().getColumnCount() > 0) {
            tblPendingReviews.getColumnModel().getColumn(0).setResizable(false);
            tblPendingReviews.getColumnModel().getColumn(2).setResizable(false);
        }

        lblLogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/54x54_PowerFitBeans.png"))); // NOI18N
        lblLogoImg.setText("jLabel1");

        lblWelcomeInstructor.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblWelcomeInstructor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWelcomeInstructor.setText("Welcome <Instructor Name>");

        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Playing <Ejercicio>"));
        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());

        lblPendingReview.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPendingReview.setText("Pending Review");

        btnVerUsuarios.setText("Ver usuarios");
        btnVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(lblWelcomeInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLogoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPendingReview, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(pnlVideoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcomeInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblLogoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblPendingReview, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnVerUsuarios))
                    .addComponent(pnlVideoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUsuariosActionPerformed
        mainForm.showAllUsers();
    }//GEN-LAST:event_btnVerUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogoImg;
    private javax.swing.JLabel lblPendingReview;
    private javax.swing.JLabel lblWelcomeInstructor;
    private javax.swing.JPanel pnlVideoPlayer;
    private javax.swing.JTable tblPendingReviews;
    // End of variables declaration//GEN-END:variables
}
