package mrnock.powerfitbeans.dialogs;

import mrnock.powerfitbeans.MainForm;

/**
 * This PnlWelcome class extends from JPanel and it is used to welcome the users
 * with a welcome message and a link to the Power Fit Beans website.
 *
 * By clicking the icon, the user will be prompted with the Login form to access
 * the app after validation.
 *
 * @author Richard Navarro {@literal <richardnavarro@paucasesnovescifp.cat>}
 * @version 2.0 Final version to submit for Unit 3 (Desarrollo de Interfaces)
 * @since 2.0
 */
public class PnlWelcome extends javax.swing.JPanel {

    /**
     * Creates new form PnlWelcome
     *
     * @param mainForm information from the MainForm screen.
     */
    public PnlWelcome(MainForm mainForm) {
        this.mainForm = mainForm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblAccessLogin = new javax.swing.JLabel();
        lblIconLogin = new javax.swing.JLabel();
        lblMoreInfo = new javax.swing.JLabel();
        lblUrlWeb = new javax.swing.JLabel();
        lblWelcomeImage = new javax.swing.JLabel();

        setLayout(null);

        lblWelcome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome to the Power Fit Beans App");
        add(lblWelcome);
        lblWelcome.setBounds(530, 40, 310, 40);

        lblAccessLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAccessLogin.setText("Click to login:");
        add(lblAccessLogin);
        lblAccessLogin.setBounds(560, 140, 150, 30);

        lblIconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-64.png"))); // NOI18N
        lblIconLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconLoginMouseClicked(evt);
            }
        });
        add(lblIconLogin);
        lblIconLogin.setBounds(720, 130, 70, 50);

        lblMoreInfo.setText("More info: ");
        add(lblMoreInfo);
        lblMoreInfo.setBounds(600, 340, 60, 16);

        lblUrlWeb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUrlWeb.setForeground(new java.awt.Color(0, 0, 255));
        lblUrlWeb.setText("www.powerfitbeans.com");
        lblUrlWeb.setToolTipText("https://paucasesnovescifp.cat/");
        lblUrlWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lblUrlWeb);
        lblUrlWeb.setBounds(660, 340, 160, 20);

        lblWelcomeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/432x432_PowerFitBeans.png"))); // NOI18N
        lblWelcomeImage.setMaximumSize(new java.awt.Dimension(112, 108));
        lblWelcomeImage.setMinimumSize(new java.awt.Dimension(112, 108));
        add(lblWelcomeImage);
        lblWelcomeImage.setBounds(10, 10, 432, 432);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method calls the validateLogin method to validate the user, enabling
     * him/her access into the app.
     */
    private void lblIconLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconLoginMouseClicked
        mainForm.validateLogin();
    }//GEN-LAST:event_lblIconLoginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccessLogin;
    private javax.swing.JLabel lblIconLogin;
    private javax.swing.JLabel lblMoreInfo;
    private javax.swing.JLabel lblUrlWeb;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcomeImage;
    // End of variables declaration//GEN-END:variables
   // private DlgLogin dlgLogin;
    private MainForm mainForm;
}
